AWSTemplateFormatVersion: 2010-09-09
Description: >-
  asset-api

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Runtime: nodejs12.x

Resources:
  GraphQlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.graphqlHandler
      Timeout: 10
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
