AWSTemplateFormatVersion: 2010-09-09
Description: >-
  asset-api

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x

Resources:
  AssetEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: assetId
          AttributeType: "S"
        - AttributeName: timestamp
          AttributeType: "S"
      KeySchema:
        - AttributeName: assetId
          KeyType: "HASH"
        - AttributeName: timestamp
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  AssetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: "S"
      KeySchema:
        - AttributeName: id
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  GraphQlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.graphqlHandler
      Timeout: 15
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssetEventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AssetTable
      Environment:
        Variables:
          ASSET_TABLE: !Ref AssetTable
          ASSET_EVENTS_TABLE: !Ref AssetEventsTable

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
